# Generated by Django 3.2.11 on 2022-02-07 20:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_remove_questions_tags'),
    ]

    operations = [
        migrations.AddField(
            model_name='questions',
            name='tags',
            field=models.ManyToManyField(to='api.Tags'),
        ),
    ]
