# Generated by Django 4.0.2 on 2022-02-07 20:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_questions_tags'),
    ]

    operations = [
        migrations.RenameField(
            model_name='questions',
            old_name='tags',
            new_name='tag',
        ),
    ]
